# database configuration for docker contained aquarium

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: db
  port: 3306
  username: aquarium
  password: aSecretAquarium

production:
  <<: *default
  database: production
  pool: 100

# use the same name to avoid issues with switching env in docker
development:
  <<: *default
  database: production 
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
